# Generated by Django 4.2.6 on 2023-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_author_alter_book_title_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="author", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book", name="title", field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(name="Author",),
    ]
