# Generated by Django 4.2.6 on 2023-11-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_authormodel_bookmodel_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.authormodel",
            ),
        ),
    ]
