# Generated by Django 4.2.6 on 2023-11-17 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_bookmodel_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaHandleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="SocialMediaHandles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handles",
                to="books.socialmediahandlemodel",
            ),
        ),
    ]
