# Generated by Django 4.2.6 on 2023-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_socialmediahandlemodel_bookmodel_socialmediahandles"),
    ]

    operations = [
        migrations.AddField(
            model_name="authormodel",
            name="hashtags",
            field=models.ManyToManyField(to="books.socialmediahandlemodel"),
        ),
    ]
