# Generated by Django 4.2.6 on 2023-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="author", field=models.CharField(max_length=255),
        ),
    ]
