# Generated by Django 4.2.6 on 2023-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serializers", "0002_address_person_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="age", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
